TARGET  := marketprice.exe
INCS = -I ../network -I ../utils
LIBS = -L ../utils -lutils -L ../network -lnetwork -lev -ljansson -lmpdec -lmysqlclient -lz -lrdkafka -lhiredis -lcurl -lssl -lcrypto -lz -lm -lpthread -ldl -lstdc++
include ../makefile.inc
