TARGET  := cachecenter
INCS = -I ../network -I ../utils
LIBS = -L ../utils -lutils -L ../network -lnetwork -lev -ljansson -lmpdec -lrdkafka -lhiredis -lcurl -lssl -lcrypto -lz -lm -lpthread -ldl
include ../makefile.inc
