TARGET  := historyreader.exe
INCS = -I ../network -I ../utils
LIBS = -L ../utils -lutils -L ../network -lnetwork -lev -ljansson -lmpdec -lmysqlclient -lz -lhiredis -lcurl -lssl -lcrypto -lz -lm -lpthread -ldl -lstdc++

include ../makefile.inc
