TARGET  := accesshttp
INCS = -I ../network -I ../utils
LIBS = -L ../utils -lutils -L ../network -lnetwork -lev -ljansson -lmpdec -lrdkafka -lz -lssl -lcrypto -lhiredis -lm -lpthread -ldl
include ../makefile.inc

